runMigrations:
    handler: src/database/lambda/runMigrations.handler
    timeout: 300
    vpc:
        securityGroupIds:
            - !Ref ProxySecurityGroup
        subnetIds:
            - !Ref PrivateSubnetA
            - !Ref PrivateSubnetB
    package:
        patterns:
            - "drizzle/**"
            - "!node_modules/**"
    environment:
        POSTGRES_DB: ${self:custom.resourceNames.postgresDB}
        POSTGRES_USERNAME: ${env:POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
        USE_RDS_PROXY: ${self:custom.useRdsProxy.${self:provider.stage}}
        RDS_CLUSTER_ENDPOINT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Address
        RDS_CLUSTER_PORT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Port

runSeed:
    handler: src/database/lambda/runSeed.handler
    timeout: 300
    vpc:
        securityGroupIds:
            - !Ref ProxySecurityGroup
        subnetIds:
            - !Ref PrivateSubnetA
            - !Ref PrivateSubnetB
    environment:
        POSTGRES_DB: ${self:custom.resourceNames.postgresDB}
        POSTGRES_USERNAME: ${env:POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
        USE_RDS_PROXY: ${self:custom.useRdsProxy.${self:provider.stage}}
        RDS_CLUSTER_ENDPOINT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Address
        RDS_CLUSTER_PORT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Port
        S3_BUCKET_NAME: ${self:custom.resourceNames.assetsBucket}

clearDatabase:
    handler: src/database/lambda/clearDatabase.handler
    timeout: 300
    vpc:
        securityGroupIds:
            - !Ref ProxySecurityGroup
        subnetIds:
            - !Ref PrivateSubnetA
            - !Ref PrivateSubnetB
    package:
        patterns:
            - "drizzle/**"
            - "!node_modules/**"
    environment:
        POSTGRES_DB: ${self:custom.resourceNames.postgresDB}
        POSTGRES_USERNAME: ${env:POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
        USE_RDS_PROXY: ${self:custom.useRdsProxy.${self:provider.stage}}
        RDS_CLUSTER_ENDPOINT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Address
        RDS_CLUSTER_PORT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Port

testDatabase:
    handler: src/database/lambda/testDatabase.handler
    timeout: 300
    vpc:
        securityGroupIds:
            - !Ref ProxySecurityGroup
        subnetIds:
            - !Ref PrivateSubnetA
            - !Ref PrivateSubnetB
    package:
        patterns:
            - "drizzle/**"
            - "!node_modules/**"
    environment:
        POSTGRES_DB: ${self:custom.resourceNames.postgresDB}
        POSTGRES_USERNAME: ${env:POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
        USE_RDS_PROXY: ${self:custom.useRdsProxy.${self:provider.stage}}
        RDS_CLUSTER_ENDPOINT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Address
        RDS_CLUSTER_PORT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Port

# seedExperiences:
#     handler: src/database/lambda/seedExperiences.handler
#     timeout: 300
#     vpc:
#         securityGroupIds:
#             - !Ref ProxySecurityGroup
#         subnetIds:
#             - !Ref PrivateSubnetA
#             - !Ref PrivateSubnetB
#     environment:
#         POSTGRES_DB: ${self:custom.resourceNames.postgresDB}
#         POSTGRES_USERNAME: ${env:POSTGRES_USERNAME}
#         USE_RDS_PROXY: true
#         ASSETS_BUCKET_NAME: ${self:custom.resourceNames.assetsBucket}
#         ASSETS_DOMAIN: !GetAtt AssetsCloudFrontDistribution.DomainName

seedCollections:
    handler: src/database/lambda/seedCollections.handler
    timeout: 300
    vpc:
        securityGroupIds:
            - !Ref ProxySecurityGroup
        subnetIds:
            - !Ref PrivateSubnetA
            - !Ref PrivateSubnetB
    environment:
        POSTGRES_DB: ${self:custom.resourceNames.postgresDB}
        POSTGRES_USERNAME: ${env:POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
        USE_RDS_PROXY: ${self:custom.useRdsProxy.${self:provider.stage}}
        RDS_CLUSTER_ENDPOINT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Address
        RDS_CLUSTER_PORT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Port

seedCollectionItems:
    handler: src/database/lambda/seedCollectionItems.handler
    timeout: 300
    vpc:
        securityGroupIds:
            - !Ref ProxySecurityGroup
        subnetIds:
            - !Ref PrivateSubnetA
            - !Ref PrivateSubnetB
    environment:
        POSTGRES_DB: ${self:custom.resourceNames.postgresDB}
        POSTGRES_USERNAME: ${env:POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
        USE_RDS_PROXY: ${self:custom.useRdsProxy.${self:provider.stage}}
        RDS_CLUSTER_ENDPOINT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Address
        RDS_CLUSTER_PORT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Port
