runMigrations:
    handler: src/database.runMigrations
    timeout: 900
    package:
        patterns:
            - db/migrations/**/*
    url:
        cors: true
    vpc:
        securityGroupIds:
            - !Ref LambdaSecurityGroup
        subnetIds:
            - !Ref PrivateSubnetA
            - !Ref PrivateSubnetB
    environment:
        DB_ENDPOINT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Address
        DB_NAME: ${self:custom.resourceNames.postgresDB}
        DB_PORT: ${env:POSTGRES_PORT}
        DB_USER: ${env:POSTGRES_USERNAME}
        DB_PASSWORD: ${env:POSTGRES_PASSWORD}

clearDatabase:
    handler: src/database.clearDatabase
    timeout: 900
    url:
        cors: true
    vpc:
        securityGroupIds:
            - !Ref LambdaSecurityGroup
        subnetIds:
            - !Ref PrivateSubnetA
            - !Ref PrivateSubnetB
    environment:
        DB_ENDPOINT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Address
        DB_NAME: ${self:custom.resourceNames.postgresDB}
        DB_PORT: ${env:POSTGRES_PORT}
        DB_USER: ${env:POSTGRES_USERNAME}
        DB_PASSWORD: ${env:POSTGRES_PASSWORD}

testDatabase:
    handler: src/database.test
    timeout: 900
    url:
        cors: true
    vpc:
        securityGroupIds:
            - !Ref LambdaSecurityGroup
        subnetIds:
            - !Ref PrivateSubnetA
            - !Ref PrivateSubnetB
    environment:
        DB_ENDPOINT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Address
        DB_NAME: ${self:custom.resourceNames.postgresDB}
        DB_PORT: ${env:POSTGRES_PORT}
        DB_USER: ${env:POSTGRES_USERNAME}
        DB_PASSWORD: ${env:POSTGRES_PASSWORD}

seedDatabase:
    handler: src/database.seedDatabase
    timeout: 900
    url:
        cors: true
    vpc:
        securityGroupIds:
            - !Ref LambdaSecurityGroup
        subnetIds:
            - !Ref PrivateSubnetA
            - !Ref PrivateSubnetB
    environment:
        DB_ENDPOINT: !GetAtt PostgresRDSServerlessCluster.Endpoint.Address
        DB_NAME: ${self:custom.resourceNames.postgresDB}
        DB_PORT: ${env:POSTGRES_PORT}
        DB_USER: ${env:POSTGRES_USERNAME}
        DB_PASSWORD: ${env:POSTGRES_PASSWORD}
