Resources:
    PostgresParameterGroup:
        Type: AWS::RDS::DBClusterParameterGroup
        Properties:
            Description: Parameter group for Aurora PostgreSQL 17.4 without SSL verification
            Family: aurora-postgresql17
            Parameters:
                shared_preload_libraries: "pg_stat_statements"
                log_statement: "all"
                log_min_duration_statement: 1000
                rds.force_ssl: 0

    PostgresRDSServerlessCluster:
        Type: AWS::RDS::DBCluster
        Properties:
            Engine: aurora-postgresql
            EngineVersion: 17.4
            EngineMode: provisioned
            DatabaseName: ${self:custom.resourceNames.postgresDB}
            Port: 5432
            MasterUsername: ${env:POSTGRES_USERNAME}
            MasterUserPassword: ${env:POSTGRES_PASSWORD}
            DeletionProtection: false
            DBClusterParameterGroupName: !Ref PostgresParameterGroup
            ServerlessV2ScalingConfiguration:
                MinCapacity: 0
                MaxCapacity: 8
            VpcSecurityGroupIds:
                - !Ref DBSecurityGroup
            DBSubnetGroupName: !Ref PostgresRDSSubnetGroup

    PostgresRDSSubnetGroup:
        Type: AWS::RDS::DBSubnetGroup
        Properties:
            DBSubnetGroupDescription: Postgres subnet group
            SubnetIds:
                - !Ref PrivateSubnetA
                - !Ref PrivateSubnetB

    PostgresInstance:
        Type: AWS::RDS::DBInstance
        Properties:
            DBClusterIdentifier: !Ref PostgresRDSServerlessCluster
            Engine: aurora-postgresql
            DBInstanceClass: db.serverless
