Resources:
    SecretsManager:
        Type: AWS::SecretsManager::Secret
        Properties:
            Name: ${self:custom.resourceNames.secretsManager}
            Description: Ohana Secrets Manager
            SecretString: !Sub '{"username":"${env:POSTGRES_USERNAME}","password":"${env:POSTGRES_PASSWORD}"}'
