name: Ohana Serverless CI/CD Pipeline

on:
    push:
        branches: [main]

jobs:
    deploy:
        environment: production
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "23.3.0"

            - name: Install dependencies
              run: npm install

            - name: Install PNPM
              run: npm install -g pnpm

            - name: Install serverless framework
              run: npm install -g serverless

            - name: Deploy
              env:
                  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: us-east-1

                  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

                  POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
                  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}

                  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
                  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
                  TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}

                  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
                  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}

              run: serverless deploy --stage prod
